version: '3'
services:

  api:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./server:/app/server:ro
    links:
      - db:db
    depends_on:
      - db
    
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - msgBoard-db:/data/db

volumes:
  msgBoard-db: 
    external: true
    name: mongodbdata